var STARTING_CURRENCY = 400;
var RESPAWN_TIME = 6;


var RANDOMIZE_NB_WAVES = 7;

var RANDOMIZE_NB_BOTS_MIN = 3;
var RANDOMIZE_NB_BOTS_MAX = 5;

var RANDOMIZE_NB_SQUADS_MIN = 3;
var RANDOMIZE_NB_SQUADS_MAX = 5;