var GlobalAttributesList =
{
    "damage penalty":{"effect_type":"negative","description_string":"X% damage penalty"},
"damage bonus":{"effect_type":"positive","description_string":"+X% damage bonus"},
"clip size penalty":{"effect_type":"negative","description_string":"X% clip size"},
"clip size bonus":{"effect_type":"positive","description_string":"+X% clip size"},
"fire rate penalty":{"effect_type":"negative","description_string":"X% slower firing speed"},
"fire rate bonus":{"effect_type":"positive","description_string":"+X% faster firing speed"},
"heal rate penalty":{"effect_type":"negative","description_string":"X% heal rate"},
"heal rate bonus":{"effect_type":"positive","description_string":"+X% heal rate"},
"ubercharge rate penalty":{"effect_type":"negative","description_string":"X% �berCharge rate"},
"ubercharge rate bonus":{"effect_type":"positive","description_string":"+X% �berCharge rate"},
"overheal bonus":{"effect_type":"positive","description_string":"+X% max overheal"},
"overheal decay penalty":{"effect_type":"negative","description_string":"X% shorter overheal time"},
"overheal decay bonus":{"effect_type":"positive","description_string":"+X% longer overheal time"},
"overheal decay disabled":{"effect_type":"positive","description_string":"Overheal bonus doesn't decay"},
"crit mod disabled":{"effect_type":"negative","description_string":"No random critical hits"},
"heal on hit for rapidfire":{"effect_type":"positive","description_string":"On Hit: Gain up to +X health"},
"add uber charge on hit":{"effect_type":"positive","description_string":"On Hit: X% �berCharge added"},
"medigun charge is crit boost":{"effect_type":"neutral","description_string":"�berCharge grants 100% critical chance"},
"tmp dmgbuff on hit":{"effect_type":"positive","description_string":"On Hit: +X% damage bonus"},
"crit vs burning players":{"effect_type":"positive","description_string":"100% critical hit vs burning players"},
"dmg penalty vs nonburning":{"effect_type":"negative","description_string":"X% damage vs non-burning players"},
"no crit vs nonburning":{"effect_type":"negative","description_string":"No critical hits vs non-burning players"},
"mod flamethrower push":{"effect_type":"negative","description_string":"No compression blast"},
"mod flamethrower back crit":{"effect_type":"positive","description_string":"100% critical hits from behind"},
"hidden secondary max ammo penalty":{"effect_type":"neutral","description_string":"unused"},
"max health additive bonus":{"effect_type":"positive","description_string":"+X max health on wearer"},
"alt-fire disabled":{"effect_type":"neutral","description_string":"#Attrib_AltFire_Disabled"},
"crit mod disabled hidden":{"effect_type":"negative","description_string":"No random critical hits"},
"alt-fire is vampire":{"effect_type":"positive","description_string":"#Attrib_AltFire_Is_Vampire"},
"fists have radial buff":{"effect_type":"neutral","description_string":"On Kill: +50 health on nearby teammatesnOn Kill: +10% Crit Chance on nearby teammates"},
"critboost on kill":{"effect_type":"positive","description_string":"On Kill: X seconds of 100% critical chance"},
"slow enemy on hit":{"effect_type":"positive","description_string":"On Hit: X% chance to slow target"},
"set cloak is feign death":{"effect_type":"neutral","description_string":"Cloak Type: Feign Death.nLeave a fake corpse on taking damagenand temporarily gain invisibility, speed and damage resistance."},
"mult cloak meter consume rate":{"effect_type":"negative","description_string":"+X% cloak drain rate"},
"mult cloak meter regen rate":{"effect_type":"positive","description_string":"+X% cloak regen rate"},
"spread penalty":{"effect_type":"negative","description_string":"X% less accurate"},
"hidden primary max ammo bonus":{"effect_type":"positive","description_string":"unused"},
"mod bat launches balls":{"effect_type":"positive","description_string":"Alt-Fire: Launches a ball that stuns opponents"},
"dmg penalty vs nonstunned":{"effect_type":"negative","description_string":"X% damage vs non-stunned players"},
"zoom speed mod disabled":{"effect_type":"positive","description_string":"No move speed penalty from zoom"},
"sniper charge per sec":{"effect_type":"positive","description_string":"+X% charge rate"},
"sniper no headshots":{"effect_type":"negative","description_string":"No headshots"},
"scattergun no reload single":{"effect_type":"neutral","description_string":"#Attrib_Scattergun_NoReloadSingle"},
"scattergun has knockback":{"effect_type":"positive","description_string":"Knockback on the target and shooter"},
"bullets per shot bonus":{"effect_type":"positive","description_string":"+X% bullets per shot"},
"sniper zoom penalty":{"effect_type":"negative","description_string":"X% zoom reduction"},
"sniper no charge":{"effect_type":"negative","description_string":"No zoom or damage charge"},
"set cloak is movement based":{"effect_type":"neutral","description_string":"Cloak Type: Motion Sensitive.nAlt-Fire: Turn invisible.  Cannot attack while invisible.  Bumping in to enemies will make you slightly visible to enemies.nCloak drain rate based on movement speed."},
"no double jump":{"effect_type":"negative","description_string":"Disables double jump"},
"absorb damage while cloaked":{"effect_type":"positive","description_string":"Absorbs X% damage while cloaked"},
"revolver use hit locations":{"effect_type":"positive","description_string":"Crits on headshot"},
"backstab shield":{"effect_type":"positive","description_string":"Blocks a single backstab attempt"},
"fire retardant":{"effect_type":"positive","description_string":"Wearer cannot ignite"},
"move speed penalty":{"effect_type":"negative","description_string":"X% slower move speed on wearer"},
"obsolete ammo penalty":{"effect_type":"neutral","description_string":"unused"},
"jarate description":{"effect_type":"neutral","description_string":"Coated enemies take mini-critsnCan be used to extinguish fires."},
"health regen":{"effect_type":"positive","description_string":"+X health regenerated per second on wearer"},
"self dmg push force increased":{"effect_type":"positive","description_string":"+X% self damage force"},
"self dmg push force decreased":{"effect_type":"negative","description_string":"X% self damage force"},
"dmg taken from fire reduced":{"effect_type":"positive","description_string":"+X% fire damage resistance on wearer"},
"dmg taken from fire increased":{"effect_type":"negative","description_string":"X% fire damage vulnerability on wearer"},
"dmg taken from crit reduced":{"effect_type":"positive","description_string":"+X% critical hit damage resistance on wearer"},
"dmg taken from crit increased":{"effect_type":"negative","description_string":"X% critical hit damage vulnerability on wearer"},
"dmg taken from blast reduced":{"effect_type":"positive","description_string":"+X% explosive damage resistance on wearer"},
"dmg taken from blast increased":{"effect_type":"negative","description_string":"X% explosive damage vulnerability on wearer"},
"dmg taken from bullets reduced":{"effect_type":"positive","description_string":"+X% bullet damage resistance on wearer"},
"dmg taken from bullets increased":{"effect_type":"negative","description_string":"X% bullet damage vulnerability on wearer"},
"increase player capture value":{"effect_type":"positive","description_string":"+X capture rate on wearer"},
"health from healers reduced":{"effect_type":"negative","description_string":"X% health from healers on wearer"},
"health from healers increased":{"effect_type":"positive","description_string":"+X% health from healers on wearer"},
"weapon burn dmg increased":{"effect_type":"positive","description_string":"+X% afterburn damage bonus"},
"weapon burn dmg reduced":{"effect_type":"negative","description_string":"X% afterburn damage penalty"},
"weapon burn time increased":{"effect_type":"positive","description_string":"+X% afterburn duration"},
"weapon burn time reduced":{"effect_type":"negative","description_string":"X% afterburn duration"},
"aiming movespeed increased":{"effect_type":"positive","description_string":"+X% faster move speed while deployed"},
"maxammo primary increased":{"effect_type":"positive","description_string":"+X% max primary ammo on wearer"},
"maxammo primary reduced":{"effect_type":"negative","description_string":"X% max primary ammo on wearer"},
"maxammo secondary increased":{"effect_type":"positive","description_string":"+X% max secondary ammo on wearer"},
"maxammo secondary reduced":{"effect_type":"negative","description_string":"X% max secondary ammo on wearer"},
"maxammo metal increased":{"effect_type":"positive","description_string":"+X% max metal on wearer"},
"maxammo metal reduced":{"effect_type":"negative","description_string":"X% max metal on wearer"},
"cloak consume rate increased":{"effect_type":"negative","description_string":"-X% cloak duration"},
"cloak consume rate decreased":{"effect_type":"positive","description_string":"+X% cloak duration"},
"cloak regen rate increased":{"effect_type":"positive","description_string":"+X% cloak regeneration rate"},
"cloak regen rate decreased":{"effect_type":"negative","description_string":"X% cloak regeneration rate"},
"minigun spinup time increased":{"effect_type":"negative","description_string":"X% slower spin up time"},
"minigun spinup time decreased":{"effect_type":"positive","description_string":"X% faster spin up time"},
"max pipebombs increased":{"effect_type":"positive","description_string":"+X max pipebombs out"},
"max pipebombs decreased":{"effect_type":"negative","description_string":"X max pipebombs out"},
"SRifle Charge rate increased":{"effect_type":"positive","description_string":"X% faster power charge"},
"SRifle Charge rate decreased":{"effect_type":"negative","description_string":"X% slower power charge"},
"Construction rate increased":{"effect_type":"positive","description_string":"Construction hit speed boost increased by X%"},
"Construction rate decreased":{"effect_type":"negative","description_string":"Construction hit speed boost decreased by X%"},
"Repair rate increased":{"effect_type":"positive","description_string":"X% faster repair rate"},
"Repair rate decreased":{"effect_type":"negative","description_string":"X% slower repair rate"},
"Reload time increased":{"effect_type":"negative","description_string":"X% slower reload time"},
"Reload time decreased":{"effect_type":"positive","description_string":"X% faster reload time"},
"selfdmg on hit for rapidfire":{"effect_type":"negative","description_string":"On Hit: X health"},
"Blast radius increased":{"effect_type":"positive","description_string":"+X% explosion radius"},
"Blast radius decreased":{"effect_type":"negative","description_string":"X% explosion radius"},
"Projectile range increased":{"effect_type":"positive","description_string":"+X% projectile range"},
"Projectile range decreased":{"effect_type":"negative","description_string":"X% projectile range"},
"Projectile speed increased":{"effect_type":"positive","description_string":"+X% projectile speed"},
"Projectile speed decreased":{"effect_type":"negative","description_string":"X% projectile speed"},
"overheal penalty":{"effect_type":"negative","description_string":"X% max overheal"},
"weapon spread bonus":{"effect_type":"positive","description_string":"X% more accurate"},
"move speed bonus":{"effect_type":"positive","description_string":"+X% faster move speed on wearer"},
"health from packs increased":{"effect_type":"positive","description_string":"+X% health from packs on wearer"},
"health from packs decreased":{"effect_type":"negative","description_string":"X% health from packs on wearer"},
"heal on hit for slowfire":{"effect_type":"positive","description_string":"On Hit: Gain up to +X health"},
"selfdmg on hit for slowfire":{"effect_type":"negative","description_string":"On Hit: X health"},
"ammo regen":{"effect_type":"positive","description_string":"+X% ammo regenerated every 5 seconds on wearer"},
"metal regen":{"effect_type":"positive","description_string":"+X metal regenerated every 5 seconds on wearer"},
"mod mini-crit airborne":{"effect_type":"positive","description_string":"Mini-crits targets launched airborne by explosions, grapple hooks or enemy attacks"},
"mod shovel damage boost":{"effect_type":"positive","description_string":"Damage increases as the user becomes injured"},
"mod soldier buff type":{"effect_type":"positive","description_string":"#Attrib_SoldierBuffType"},
"dmg falloff increased":{"effect_type":"negative","description_string":"#Attrib_Dmg_Falloff_Increased"},
"dmg falloff decreased":{"effect_type":"positive","description_string":"X% splash damage fall off"},
"sticky detonate mode":{"effect_type":"positive","description_string":"Detonates stickybombs near the crosshair and directly under your feet"},
"sticky arm time penalty":{"effect_type":"negative","description_string":"X sec slower bomb arm time"},
"stickies detonate stickies":{"effect_type":"positive","description_string":"Able to destroy enemy stickybombs"},
"mod demo buff type":{"effect_type":"positive","description_string":"#Attrib_DemoBuffType"},
"speed boost when active":{"effect_type":"positive","description_string":"X% speed boost while active weapon"},
"mod wrench builds minisentry":{"effect_type":"negative","description_string":"Replaces the Sentry with a Mini-Sentry"},
"max health additive penalty":{"effect_type":"negative","description_string":"X max health on wearer"},
"sticky arm time bonus":{"effect_type":"positive","description_string":"X sec faster bomb arm time"},
"sticky air burst mode":{"effect_type":"negative","description_string":"Launched bombs shatter on surfaces"},
"provide on active":{"effect_type":"neutral","description_string":"When weapon is active:"},
"health drain":{"effect_type":"negative","description_string":"X health drained per second on wearer"},
"medic regen bonus":{"effect_type":"positive","description_string":"+X% natural regen rate"},
"medic regen penalty":{"effect_type":"negative","description_string":"-X% natural regen rate"},
"community description":{"effect_type":"neutral","description_string":"Given to valuable Community Contributors"},
"soldier model index":{"effect_type":"neutral","description_string":"Medal no. X"},
"attach particle effect":{"effect_type":"unusual","description_string":" Unusual Effect: X"},
"rocket jump damage reduction":{"effect_type":"positive","description_string":"X% blast damage from rocket jumps"},
"mod sentry killed revenge":{"effect_type":"positive","description_string":"Gain 2 revenge crits for each sentry kill andn1 for each sentry assist when your sentry is destroyed."},
"dmg bonus vs buildings":{"effect_type":"positive","description_string":"+X% damage vs buildings"},
"dmg penalty vs players":{"effect_type":"negative","description_string":"X% damage vs players"},
"lunchbox adds maxhealth bonus":{"effect_type":"positive","description_string":"Adds +50 max health for 30 seconds"},
"hidden maxhealth non buffed":{"effect_type":"positive","description_string":"+X max health on wearer"},
"selfmade description":{"effect_type":"neutral","description_string":"I made this!"},
"set item tint RGB":{"effect_type":"neutral","description_string":"Item tint color code: X"},
"custom employee number":{"effect_type":"neutral","description_string":"Hire Date: X"},
"lunchbox adds minicrits":{"effect_type":"neutral","description_string":"Sets weapon mode #X"},
"taunt is highfive":{"effect_type":"neutral","description_string":"X% damage penalty"},
"damage applies to sappers":{"effect_type":"positive","description_string":"Damage removes Sappers"},
"Wrench index":{"effect_type":"neutral","description_string":"Wrench no. X"},
"building cost reduction":{"effect_type":"positive","description_string":"X metal reduction in building cost"},
"bleeding duration":{"effect_type":"positive","description_string":"On Hit: Bleed for X seconds"},
"turn to gold":{"effect_type":"positive","description_string":"Imbued with an ancient power"},
"DEPRECATED socketed item definition id DEPRECATED ":{"effect_type":"positive","description_string":"#Attrib_Socket"},
"custom texture lo":{"effect_type":"positive","description_string":"Custom Texture"},
"cannot trade":{"effect_type":"neutral","description_string":"Not Tradable"},
"disguise on backstab":{"effect_type":"positive","description_string":"Upon a successful backstab against a human target, you rapidly disguise as your victim"},
"cannot disguise":{"effect_type":"negative","description_string":"Wearer cannot disguise"},
"silent killer":{"effect_type":"positive","description_string":"Silent Killer: No attack noise from backstabs"},
"disguise speed penalty":{"effect_type":"negative","description_string":"X sec slower disguise speed"},
"add cloak on kill":{"effect_type":"positive","description_string":"+X% cloak on kill"},
"SET BONUS: cloak blink time penalty":{"effect_type":"negative","description_string":"X sec longer cloak blink time"},
"SET BONUS: quiet unstealth":{"effect_type":"positive","description_string":"Reduced decloak sound volume"},
"flame size penalty":{"effect_type":"negative","description_string":"X% less flame spread area"},
"flame size bonus":{"effect_type":"positive","description_string":"+X% more flame spread area"},
"flame life penalty":{"effect_type":"negative","description_string":"X% less flame distance"},
"flame life bonus":{"effect_type":"positive","description_string":"+X% more flame distance"},
"charged airblast":{"effect_type":"neutral","description_string":"Airblast can now be charged, which will push enemies further"},
"add cloak on hit":{"effect_type":"positive","description_string":"+X% cloak on hit"},
"disguise damage reduction":{"effect_type":"positive","description_string":"#Attrib_DisguiseDamageReduction"},
"disguise no burn":{"effect_type":"positive","description_string":"Immune to fire damage while disguised"},
"SET BONUS: dmg from sentry reduced":{"effect_type":"positive","description_string":"+X% sentry damage resistance on wearer"},
"airblast cost increased":{"effect_type":"negative","description_string":"+X% airblast cost"},
"airblast cost decreased":{"effect_type":"positive","description_string":"X% airblast cost"},
"purchased":{"effect_type":"neutral","description_string":"Purchased: Not Tradable or Usable in Crafting"},
"flame ammopersec increased":{"effect_type":"negative","description_string":"+X% flamethrower ammo consumed per second"},
"flame ammopersec decreased":{"effect_type":"positive","description_string":"X% flamethrower ammo consumed per second"},
"jarate duration":{"effect_type":"positive","description_string":"On Scoped Hit: Jarate target for 2 to X seconds based on amount charged.nHeadshots or fully charged shots cause an explosion of Jarate."},
"SET BONUS: no death from headshots":{"effect_type":"positive","description_string":"The wearer cannot be killed by headshots"},
"deploy time increased":{"effect_type":"negative","description_string":"X% longer weapon switch"},
"deploy time decreased":{"effect_type":"positive","description_string":"X% faster weapon switch"},
"minicrits become crits":{"effect_type":"positive","description_string":"Crits whenever it would normally mini-crit"},
"heal on kill":{"effect_type":"positive","description_string":"+X health restored on kill"},
"no self blast dmg":{"effect_type":"positive","description_string":"No self inflicted blast damage taken"},
"slow enemy on hit major":{"effect_type":"positive","description_string":"On Hit: Slow target movement by 40% for Xs"},
"aiming movespeed decreased":{"effect_type":"negative","description_string":"X% slower move speed while deployed"},
"duel loser account id":{"effect_type":"neutral","description_string":"#Attrib_DuelLoserAccountID"},
"event date":{"effect_type":"neutral","description_string":"Date Received: X"},
"gifter account id":{"effect_type":"positive","description_string":"nGift from: X"},
"set supply crate series":{"effect_type":"positive","description_string":"Crate Series #X"},
"preserve ubercharge":{"effect_type":"positive","description_string":"On death up to X% of your storedn�berCharge is retained"},
"elevate quality":{"effect_type":"positive","description_string":"#Attrib_ElevateQuality"},
"active health regen":{"effect_type":"positive","description_string":"+X health regenerated per second on wearer"},
"active health degen":{"effect_type":"negative","description_string":"X health drained per second on wearer"},
"referenced item id low":{"effect_type":"negative","description_string":""},
"referenced item id high":{"effect_type":"negative","description_string":""},
"referenced item def UPDATED":{"effect_type":"neutral","description_string":"Contains: X"},
"always tradable":{"effect_type":"negative","description_string":"Always Tradable"},
"noise maker":{"effect_type":"neutral","description_string":"Noise Maker"},
"halloween item":{"effect_type":"positive","description_string":"This is a special Halloween X item"},
"collection bits DEPRECATED":{"effect_type":"positive","description_string":"This is a special Halloween X item"},
"switch from wep deploy time decreased":{"effect_type":"positive","description_string":"This weapon holsters X% faster"},
"enables aoe heal":{"effect_type":"positive","description_string":"Alt-Fire: Applies a healing effect to all nearby teammates"},
"gesture speed increase":{"effect_type":"positive","description_string":"+X% faster taunt speed on wearer"},
"charge time increased":{"effect_type":"positive","description_string":"X sec increase in charge duration"},
"drop health pack on kill":{"effect_type":"positive","description_string":"On Kill: A small health pack is dropped"},
"hit self on miss":{"effect_type":"negative","description_string":"On Miss: Hit yourself. Idiot."},
"dmg from ranged reduced":{"effect_type":"positive","description_string":"X% damage from ranged sources while active"},
"dmg from melee increased":{"effect_type":"negative","description_string":"+X% damage from melee sources while active"},
"blast dmg to self increased":{"effect_type":"negative","description_string":"+X% damage to self"},
"Set DamageType Ignite":{"effect_type":"positive","description_string":"On Hit: target is engulfed in flames"},
"minicrit vs burning player":{"effect_type":"positive","description_string":"100% mini-crits vs burning players"},
"tradable after date":{"effect_type":"negative","description_string":"nTradable After: X"},
"force level display":{"effect_type":"positive","description_string":""},
"kill eater":{"effect_type":"positive","description_string":""},
"apply z velocity on damage":{"effect_type":"positive","description_string":""},
"apply look velocity on damage":{"effect_type":"positive","description_string":"#Attrib_Knockback"},
"sanguisuge":{"effect_type":"positive","description_string":"On Backstab: Absorbs the health from your victim."},
"mark for death":{"effect_type":"positive","description_string":"On Hit: One target at a time is marked for death, causing all damage taken to be mini-crits"},
"decapitate type":{"effect_type":"positive","description_string":"X% damage penalty"},
"restore health on kill":{"effect_type":"positive","description_string":"Gain X% of base health on kill"},
"mult decloak rate":{"effect_type":"positive","description_string":"#Attrib_DecloakRate"},
"mult sniper charge after bodyshot":{"effect_type":"positive","description_string":"On Scoped Bodyshot: Rifle charge rate increased by X%"},
"mult sniper charge after miss":{"effect_type":"negative","description_string":"On Scoped Miss: Rifle charge rate decreased by X%"},
"dmg bonus while half dead":{"effect_type":"positive","description_string":"X% increase in damage when health <50% of max"},
"dmg penalty while half alive":{"effect_type":"negative","description_string":"X% decrease in damage when health >50% of max"},
"honorbound":{"effect_type":"negative","description_string":"Honorbound: Once drawn sheathing deals 50 damage to yourself unless it kills."},
"custom texture hi":{"effect_type":"positive","description_string":"Custom Texture"},
"makers mark id":{"effect_type":"positive","description_string":"Crafted by X"},
"unique craft index":{"effect_type":"positive","description_string":""},
"mod medic killed revenge":{"effect_type":"positive","description_string":"When the medic healing you is killed youngain 2 revenge crits"},
"medigun charge is megaheal":{"effect_type":"neutral","description_string":"�berCharge increases healing by 300% and grants immunity to movement-impairing effects"},
"mod medic killed minicrit boost":{"effect_type":"positive","description_string":"When the medic healing you is killednyou gain mini-crit boost for X seconds"},
"mod medic healed damage bonus":{"effect_type":"positive","description_string":"While a medic is healing you,nthis weapon's damage is increased by X%"},
"mod medic healed deploy time penalty":{"effect_type":"negative","description_string":"While not being healed by a medic,nyour weapon switch time is X% longer"},
"mod shovel speed boost":{"effect_type":"positive","description_string":"Move speed increases as the user becomes injured"},
"mod weapon blocks healing":{"effect_type":"negative","description_string":"Blocks healing while in use"},
"mult sniper charge after headshot":{"effect_type":"positive","description_string":"On Scoped Headshot: Rifle charge rate increased by X%"},
"minigun no spin sounds":{"effect_type":"positive","description_string":"Silent Killer: No barrel spin sound"},
"ubercharge rate bonus for healer":{"effect_type":"positive","description_string":"+X% �berCharge rate for the medic healing younThis effect does not work in the respawn room"},
"reload time decreased while healed":{"effect_type":"positive","description_string":"X% faster reload time while being healed"},
"reload time increased hidden":{"effect_type":"negative","description_string":"X% slower reload time"},
"mod medic killed marked for death":{"effect_type":"positive","description_string":"When the medic healing you is killednthe killer becomes marked for death"},
"mod rage on hit penalty":{"effect_type":"negative","description_string":"X% rage lost on hit"},
"mod rage on hit bonus":{"effect_type":"positive","description_string":"X% rage gained on hit"},
"mod rage damage boost":{"effect_type":"positive","description_string":"Gains a damage bonus as rage increases, up to X%"},
"mult charge turn control":{"effect_type":"positive","description_string":"+X% increase in turning control while charging"},
"no charge impact range":{"effect_type":"positive","description_string":"Can deal charge impact damage at any range"},
"charge impact damage increased":{"effect_type":"positive","description_string":"+X% increase in charge impact damage"},
"charge recharge rate increased":{"effect_type":"positive","description_string":"+X% increase in charge recharge rate"},
"air dash count":{"effect_type":"positive","description_string":"Grants Triple Jump: The third jump deals 10 damage when used"},
"speed buff ally":{"effect_type":"positive","description_string":"On Hit Ally: Boosts both players' speed for several seconds"},
"damage force reduction":{"effect_type":"positive","description_string":"X% reduction in push force taken from damage"},
"mult cloak rate":{"effect_type":"negative","description_string":"X sec increase in time to cloak"},
"airblast functionality flags":{"effect_type":"positive","description_string":""},
"airblast pushback scale":{"effect_type":"positive","description_string":"+X% airblast push force"},
"mult airblast refire time":{"effect_type":"positive","description_string":""},
"airblast vertical pushback scale":{"effect_type":"positive","description_string":""},
"ammo becomes health":{"effect_type":"positive","description_string":"Ammo collected from ammo boxes becomes health"},
"boots falling stomp":{"effect_type":"positive","description_string":"Deals 3x falling damage to the player you land on"},
"deflection size multiplier":{"effect_type":"positive","description_string":"#Attrib_DeflectionSizeMultiplier"},
"set item tint RGB 2":{"effect_type":"neutral","description_string":"Item tint color code: X"},
"saxxy award category":{"effect_type":"positive","description_string":"Winner: X %s2n"},
"melee bounds multiplier":{"effect_type":"positive","description_string":""},
"melee range multiplier":{"effect_type":"positive","description_string":"X% increased melee attack range"},
"mod mini-crit airborne deploy":{"effect_type":"positive","description_string":""},
"projectile penetration":{"effect_type":"positive","description_string":"Projectiles penetrate enemy players"},
"mod crit while airborne":{"effect_type":"positive","description_string":"Deals crits while the wielder is rocket jumping"},
"mult sniper charge penalty DISPLAY ONLY":{"effect_type":"negative","description_string":"Base charge rate decreased by X%"},
"mod see enemy health":{"effect_type":"positive","description_string":"Allows you to see enemy health"},
"powerup max charges":{"effect_type":"positive","description_string":"Holds a maximum of X charges"},
"powerup charges":{"effect_type":"positive","description_string":"Currently holds X charges"},
"powerup duration":{"effect_type":"positive","description_string":"Each charge lasts X seconds"},
"critboost":{"effect_type":"positive","description_string":"Consumable: Become Crit Boosted for 5 secondsn(and double your sentry's firing speed)"},
"ubercharge":{"effect_type":"positive","description_string":"Consumable: Become �bercharged for 5 secondsn(and shield your sentry from damage)"},
"cancel falling damage":{"effect_type":"positive","description_string":"Wearer never takes falling damage"},
"bidirectional teleport":{"effect_type":"positive","description_string":"Teleporters can be used in both directions"},
"multiple sentries":{"effect_type":"positive","description_string":"#Attrib_MultipleSentries"},
"effect bar recharge rate increased":{"effect_type":"positive","description_string":"+X% increase in recharge rate"},
"maxammo grenades1 increased":{"effect_type":"positive","description_string":"+X% max misc ammo on wearer"},
"override projectile type":{"effect_type":"positive","description_string":""},
"energy weapon no ammo":{"effect_type":"positive","description_string":"Does not require ammo"},
"energy weapon charged shot":{"effect_type":"positive","description_string":"Alt-Fire: A charged shot thatnmini-crits players, sets them on firenand disables buildings for 4 sec"},
"energy weapon penetration":{"effect_type":"positive","description_string":"Projectile penetrates enemy targets"},
"energy weapon no hurt building":{"effect_type":"negative","description_string":"Deals only 20% damage to buildings"},
"energy weapon no deflect":{"effect_type":"positive","description_string":"Projectile cannot be deflected"},
"engy building health bonus":{"effect_type":"positive","description_string":"+X% max building health"},
"engy sentry damage bonus":{"effect_type":"positive","description_string":"+X% Sentry Gun damage bonus"},
"no crit boost":{"effect_type":"negative","description_string":"Cannot be crit boosted"},
"centerfire projectile":{"effect_type":"positive","description_string":"#Attrib_CenterFireProjectile"},
"kill eater score type":{"effect_type":"positive","description_string":""},
"kill eater score type 2":{"effect_type":"positive","description_string":""},
"kill eater 2":{"effect_type":"positive","description_string":""},
"has pipboy build interface":{"effect_type":"positive","description_string":""},
"sapper kills collect crits":{"effect_type":"positive","description_string":"Gives one guaranteed critical hit for eachnbuilding destroyed with your sapper attachednor backstab kill"},
"sniper only fire zoomed":{"effect_type":"negative","description_string":"Cannot fire unless zoomed"},
"mod ammo per shot":{"effect_type":"negative","description_string":"Per Shot: -X ammo"},
"add onhit addammo":{"effect_type":"positive","description_string":"On Hit: damage dealt is returned as ammo"},
"electrical airblast DISPLAY ONLY":{"effect_type":"positive","description_string":"Alt-Fire: -15 ammo, destroy projectiles"},
"mod use metal ammo type":{"effect_type":"negative","description_string":"Uses metal for ammo"},
"expiration date":{"effect_type":"neutral","description_string":"This item will expire on X."},
"mod max primary clip override":{"effect_type":"positive","description_string":""},
"sniper full charge damage bonus":{"effect_type":"positive","description_string":"On Full Charge: +X% damage per shot"},
"sniper fires tracer":{"effect_type":"negative","description_string":"Fires tracer rounds"},
"sniper no headshot without full charge":{"effect_type":"negative","description_string":"No headshots when not fully charged"},
"mod no reload DISPLAY ONLY":{"effect_type":"positive","description_string":"No reload necessary"},
"sniper penetrate players when charged":{"effect_type":"positive","description_string":"On Full Charge: Projectiles penetrate players"},
"crit kill will gib":{"effect_type":"positive","description_string":"Killing an enemy with a critical hit will dismember your victim. Painfully."},
"recall":{"effect_type":"positive","description_string":"Consumable: Instantly teleport to spawn"},
"unlimited quantity":{"effect_type":"positive","description_string":"Unlimited use"},
"disable weapon hiding for animations":{"effect_type":"positive","description_string":""},
"applies snare effect":{"effect_type":"positive","description_string":"X% movement speed on targets"},
"uber duration bonus":{"effect_type":"positive","description_string":"�ber duration increased X seconds"},
"refill_ammo":{"effect_type":"positive","description_string":"Consumable: Instantly refill all weapon clips and ammo"},
"store sort override DEPRECATED":{"effect_type":"neutral","description_string":"#Attrib_AlternateRocketEffect"},
"faster reload rate":{"effect_type":"positive","description_string":"+X% faster reload time"},
"increase buff duration":{"effect_type":"positive","description_string":"+X% buff duration"},
"robo sapper":{"effect_type":"positive","description_string":"Increased robot Sapper radius and duration"},
"build rate bonus":{"effect_type":"positive","description_string":"+X% faster build speed"},
"taunt is press and hold":{"effect_type":"neutral","description_string":"X% damage penalty"},
"attack projectiles":{"effect_type":"positive","description_string":"Bullets destroy rockets and grenades in-flight.  Increased accuracy and frequency per-level."},
"accuracy scales damage":{"effect_type":"positive","description_string":"Accuracy scales damage"},
"currency bonus":{"effect_type":"positive","description_string":"+X% bonus currency from packs"},
"increased jump height":{"effect_type":"positive","description_string":"+X% greater jump height when active"},
"building instant upgrade":{"effect_type":"positive","description_string":"Consumable: Instantly upgrade all buildings to max level"},
"disable fancy class select anim":{"effect_type":"neutral","description_string":""},
"airblast vulnerability multiplier":{"effect_type":"negative","description_string":"+X% increased airblast vulnerability"},
"override footstep sound set":{"effect_type":"positive","description_string":""},
"spawn with physics toy":{"effect_type":"positive","description_string":""},
"fish damage override":{"effect_type":"positive","description_string":""},
"SET BONUS: special dsp":{"effect_type":"positive","description_string":""},
"bombinomicon effect on death":{"effect_type":"positive","description_string":"Explode spectacularly on death"},
"clip size bonus upgrade":{"effect_type":"positive","description_string":"+X% clip size"},
"hide enemy health":{"effect_type":"negative","description_string":"Unable to see enemy health"},
"subtract victim medigun charge on hit":{"effect_type":"positive","description_string":"On Hit: Victim loses up to X% Medigun charge"},
"subtract victim cloak on hit":{"effect_type":"positive","description_string":"On Hit: Victim loses up to X% cloak"},
"reveal cloaked victim on hit":{"effect_type":"positive","description_string":"On Hit Spy: Reveal cloaked Spy"},
"reveal disguised victim on hit":{"effect_type":"positive","description_string":"On Hit Spy: Reveal disguised Spy"},
"jarate backstabber":{"effect_type":"positive","description_string":"When backstabbed: Jarate attacker"},
"engy sentry fire rate increased":{"effect_type":"positive","description_string":"+X% sentry firing speed"},
"engy sentry radius increased":{"effect_type":"positive","description_string":"+X% sentry range"},
"engy dispenser radius increased":{"effect_type":"positive","description_string":"+X% dispenser range"},
"mod bat launches ornaments":{"effect_type":"positive","description_string":"Alt-Fire: Launches a festive ornament that shatters causing bleed"},
"freeze backstab victim":{"effect_type":"negative","description_string":"Backstab turns victim to ice"},
"fire rate penalty HIDDEN":{"effect_type":"negative","description_string":""},
"energy weapon no drain":{"effect_type":"positive","description_string":""},
"ragdolls become ash":{"effect_type":"positive","description_string":""},
"engy disposable sentries":{"effect_type":"positive","description_string":"Build +X additional disposable-sentry"},
"alt fire teleport to spawn":{"effect_type":"positive","description_string":"Press your reload key to choose to teleport to spawn or your exit teleporter"},
"cannot pick up buildings":{"effect_type":"negative","description_string":"Cannot carry buildings"},
"stun enemies wielding same weapon":{"effect_type":"positive","description_string":"Stuns enemies who are also wielding this weapon"},
"mod ammo per shot missed DISPLAY ONLY":{"effect_type":"negative","description_string":"Per Shot Missed: -X ammo"},
"airblast disabled":{"effect_type":"negative","description_string":"No airblast"},
"increase buff duration HIDDEN":{"effect_type":"positive","description_string":"+X% buff duration"},
"crit forces victim to laugh":{"effect_type":"positive","description_string":"Critical hit forces victim to laugh"},
"melts in fire":{"effect_type":"negative","description_string":"Melts in fire, regenerates in X seconds and by picking up ammo"},
"damage all connected":{"effect_type":"positive","description_string":"All players connected via Medigun beams are hit"},
"become fireproof on hit by fire":{"effect_type":"positive","description_string":"On Hit by Fire: Fireproof for 1 second and Afterburn immunity for X seconds"},
"crit from behind":{"effect_type":"positive","description_string":"Always critical hit from behind"},
"crit does no damage":{"effect_type":"negative","description_string":"Critical hits do no damage"},
"add jingle to footsteps":{"effect_type":"negative","description_string":"Jingle all the way"},
"set icicle knife mode":{"effect_type":"negative","description_string":"#Attrib_SetIcicleKnifeMode"},
"mod stun waist high airborne":{"effect_type":"positive","description_string":"On Hit: If enemy's belt is at or above eye level,nstun them for X seconds"},
"extinguish earns revenge crits":{"effect_type":"positive","description_string":"Alt-Fire: Extinguish teammates to gain guaranteed critical hits"},
"burn damage earns rage":{"effect_type":"positive","description_string":"Build 'Mmmph' by dealing damage.nAlt-Fire on full 'Mmmph': Taunt to gain crit for several seconds.nInvulnerable while 'Mmmph' taunting."},
"tickle enemies wielding same weapon":{"effect_type":"positive","description_string":"On Hit: Force enemies to laugh who are also wearing this item"},
"attach particle effect static":{"effect_type":"neutral","description_string":""},
"cosmetic taunt sound":{"effect_type":"positive","description_string":"#Attrib_TauntSoundSuccess"},
"accepted wedding ring account id 1":{"effect_type":"positive","description_string":"A perpetual bond of commitment between X"},
"accepted wedding ring account id 2":{"effect_type":"positive","description_string":"and X, forever and ever and ever. XoXoX"},
"tool escrow until date":{"effect_type":"negative","description_string":"Usable After: X"},
"generate rage on damage":{"effect_type":"positive","description_string":"Generate Rage by dealing damage.  When fully charged, press the Special-Attack key to activate knockback."},
"aiming no flinch":{"effect_type":"positive","description_string":"No flinching when aiming and fully charged"},
"aiming knockback resistance":{"effect_type":"positive","description_string":"Knockback reduced by X% when aiming"},
"sniper aiming movespeed decreased":{"effect_type":"negative","description_string":"X% slower move speed when aiming"},
"kill eater user 1":{"effect_type":"positive","description_string":""},
"kill eater user score type 1":{"effect_type":"positive","description_string":""},
"kill eater user 2":{"effect_type":"positive","description_string":""},
"kill eater user score type 2":{"effect_type":"positive","description_string":""},
"kill eater user 3":{"effect_type":"positive","description_string":""},
"kill eater user score type 3":{"effect_type":"positive","description_string":""},
"strange part new counter ID":{"effect_type":"positive","description_string":""},
"mvm completed challenges bitmask":{"effect_type":"positive","description_string":""},
"rage on kill":{"effect_type":"positive","description_string":"Gain Focus on kills and assists"},
"kill eater kill type":{"effect_type":"positive","description_string":""},
"shot penetrate all players":{"effect_type":"positive","description_string":"Shots go through multiple enemies"},
"headshot damage increase":{"effect_type":"positive","description_string":"Headshots deal an extra +X% damage"},
"SET BONUS: mystery solving time decrease":{"effect_type":"positive","description_string":"Reduces mystery solving time by up to X%"},
"damage penalty on bodyshot":{"effect_type":"negative","description_string":"X% damage on body shot"},
"sniper rage DISPLAY ONLY":{"effect_type":"positive","description_string":"Press 'Reload' to activate focusnIn Focus: +25% faster charge and no unscoping."},
"fire rate bonus HIDDEN":{"effect_type":"positive","description_string":"+X% faster firing speed"},
"explosive sniper shot":{"effect_type":"positive","description_string":"Increased headshot explosion radius and damage to nearby enemies"},
"melee attack rate bonus":{"effect_type":"positive","description_string":"+X% faster melee attack speed"},
"projectile penetration heavy":{"effect_type":"positive","description_string":"Bullets penetrate +X enemies"},
"rage on assists":{"effect_type":"positive","description_string":"#Attrib_RageGainOnAssists"},
"armor piercing":{"effect_type":"positive","description_string":"Increase backstab damage against Giant Robots by X%"},
"cannot pick up intelligence":{"effect_type":"negative","description_string":"Wearer cannot carry the intelligence briefcase or PASS Time JACK"},
"SET BONUS: chance of hunger decrease":{"effect_type":"positive","description_string":"Reduces chance of hunger by up to X%"},
"cannot be backstabbed":{"effect_type":"positive","description_string":"Cannot be backstabbed"},
"squad surplus claimer id DEPRECATED":{"effect_type":"positive","description_string":"Squad surplus claimed by: X"},
"share consumable with patient":{"effect_type":"positive","description_string":"Using your Power Up Canteen will apply the same bonus effect to your heal target"},
"airblast vertical vulnerability multiplier":{"effect_type":"positive","description_string":"#Attrib_AirBlastVerticalVulnerabilityMultipier"},
"vision opt in flags":{"effect_type":"positive","description_string":""},
"crit vs disguised players":{"effect_type":"positive","description_string":"100% critical hit vs disguised players"},
"crit vs non burning players":{"effect_type":"positive","description_string":"100% critical hit vs non-burning players"},
"kill forces attacker to laugh":{"effect_type":"positive","description_string":"On Kill: Burst into joyous laughter"},
"damage bonus while disguised":{"effect_type":"positive","description_string":"+X% damage bonus while disguised"},
"projectile spread angle penalty":{"effect_type":"negative","description_string":"+X degrees random projectile deviation"},
"dmg taken increased":{"effect_type":"negative","description_string":"X% damage vulnerability on wearer"},
"auto fires full clip":{"effect_type":"positive","description_string":"Hold Fire to load up to three rocketsnRelease Fire to unleash the barrage"},
"self mark for death":{"effect_type":"negative","description_string":"You are marked for death while active, and for short period after switching weapons"},
"counts as assister is some kind of pet this update is going to be awesome":{"effect_type":"positive","description_string":""},
"mod flaregun fires pellets with knockback":{"effect_type":"positive","description_string":"Flare knocks back target on hitnand explodes when it hits the ground.nIncreased knock back on burning players"},
"can overload":{"effect_type":"negative","description_string":"Overloading the chamber will cause a misfire"},
"boost on damage":{"effect_type":"positive","description_string":"On Hit: Builds BoostnRun speed increased with Boost"},
"hype resets on jump":{"effect_type":"negative","description_string":"Boost reduced on air jumps"},
"pyro year number":{"effect_type":"positive","description_string":"Witnessed the X inferno"},
"no primary ammo from dispensers while active":{"effect_type":"negative","description_string":"No ammo from dispensers when active"},
"pyrovision only DISPLAY ONLY":{"effect_type":"negative","description_string":"Only visible in Pyroland"},
"clip size penalty HIDDEN":{"effect_type":"negative","description_string":"X% clip size"},
"sapper damage bonus":{"effect_type":"positive","description_string":"+X% sapper damage bonus"},
"sapper damage penalty":{"effect_type":"negative","description_string":"X% sapper damage penalty"},
"sapper damage leaches health":{"effect_type":"positive","description_string":"+X health regenerated per second for each active sapper"},
"sapper health bonus":{"effect_type":"positive","description_string":"X% sapper health bonus"},
"sapper health penalty":{"effect_type":"negative","description_string":"X% sapper health penalty"},
"ring of fire while aiming":{"effect_type":"positive","description_string":"Creates a ring of flames while spun up"},
"uses ammo while aiming":{"effect_type":"negative","description_string":"Consumes an additional X ammo per second while spun up"},
"sapper degenerates buildings":{"effect_type":"positive","description_string":"Reverses enemy building construction"},
"sapper damage penalty hidden":{"effect_type":"negative","description_string":"X% sapper damage penalty"},
"cleaver description":{"effect_type":"positive","description_string":"Throw at your enemies to make them bleed!nLong distance hits cause mini-crits"},
"ragdolls plasma effect":{"effect_type":"positive","description_string":""},
"crit vs stunned players":{"effect_type":"positive","description_string":"100% critical hit vs stunned players"},
"crit vs wet players":{"effect_type":"positive","description_string":"100% critical hit vs wet players"},
"override item level desc string":{"effect_type":"positive","description_string":""},
"clip size upgrade atomic":{"effect_type":"positive","description_string":"+X clip size"},
"auto fires full clip all at once":{"effect_type":"positive","description_string":"#Attrib_AutoFiresFullClipAllAtOnce"},
"major move speed bonus":{"effect_type":"positive","description_string":""},
"major increased jump height":{"effect_type":"positive","description_string":""},
"head scale":{"effect_type":"negative","description_string":"Disables double jump"},
"pyrovision opt in DISPLAY ONLY":{"effect_type":"positive","description_string":"#Attrib_PyroVisionOptIn"},
"halloweenvision opt in DISPLAY ONLY":{"effect_type":"positive","description_string":""},
"halloweenvision filter DISPLAY ONLY":{"effect_type":"negative","description_string":""},
"player skin override":{"effect_type":"positive","description_string":"#Attrib_PlayerSkinOverride"},
"never craftable":{"effect_type":"neutral","description_string":""},
"zombiezombiezombiezombie":{"effect_type":"neutral","description_string":""},
"sapper voice pak":{"effect_type":"positive","description_string":"#Attrib_Sapper_Voice_Pak"},
"sapper voice pak idle wait":{"effect_type":"positive","description_string":"#Attrib_Sapper_Voice_Pak_Idle_Wait"},
"merasmus hat level display ONLY":{"effect_type":"positive","description_string":"Killed Merasmus at level X"},
"strange restriction type 1":{"effect_type":"positive","description_string":""},
"strange restriction value 1":{"effect_type":"positive","description_string":""},
"strange restriction type 2":{"effect_type":"positive","description_string":""},
"strange restriction value 2":{"effect_type":"positive","description_string":""},
"strange restriction user type 1":{"effect_type":"positive","description_string":""},
"strange restriction user value 1":{"effect_type":"positive","description_string":""},
"strange restriction user type 2":{"effect_type":"positive","description_string":""},
"strange restriction user value 2":{"effect_type":"positive","description_string":""},
"strange restriction user type 3":{"effect_type":"positive","description_string":""},
"strange restriction user value 3":{"effect_type":"positive","description_string":""},
"engineer sentry build rate multiplier":{"effect_type":"positive","description_string":"Sentry build speed increased by X%"},
"engineer teleporter build rate multiplier":{"effect_type":"positive","description_string":"Increases teleporter build speed by X%."},
"grenade launcher mortar mode":{"effect_type":"neutral","description_string":"Cannonballs have a fuse time of 1 second; fuses can be primed to explode earlier by holding down the fire key."},
"grenade not explode on impact":{"effect_type":"negative","description_string":"Cannonballs do not explode on impact"},
"strange score selector":{"effect_type":"positive","description_string":""},
"engineer building teleporting pickup":{"effect_type":"positive","description_string":"Alt-Fire: Use X metal to pick up your targeted building from long range"},
"grenade damage reduction on world contact":{"effect_type":"negative","description_string":"X% damage on contact with surfaces"},
"engineer rage on dmg":{"effect_type":"positive","description_string":"Generate building rescue energy on damage"},
"mark for death on building pickup":{"effect_type":"negative","description_string":"Self mark for death when hauling buildings"},
"medigun charge is resists":{"effect_type":"positive","description_string":"Press your reload key to cycle through resist types.nWhile healing, provides you and your target with a constant 10% resistance to the selected damage type."},
"arrow heals buildings":{"effect_type":"positive","description_string":"Fires a special bolt that can repair friendly buildings"},
"Projectile speed increased HIDDEN":{"effect_type":"positive","description_string":"+X% projectile speed"},
"damage bonus HIDDEN":{"effect_type":"positive","description_string":"+X% damage bonus"},
"cannonball push back":{"effect_type":"positive","description_string":"Cannonballs push players back on impact"},
"rage giving scale":{"effect_type":"positive","description_string":""},
"overheal fill rate reduced":{"effect_type":"negative","description_string":"X% Overheal build rate."},
"canteen specialist":{"effect_type":"positive","description_string":"Share Canteens with your heal target.n+1 duration, -10 price per point (minimum cost: 5)"},
"overheal expert":{"effect_type":"positive","description_string":"+25% more overheal, +50% longer duration per point."},
"mad milk syringes":{"effect_type":"positive","description_string":"Syringes deliver a highly concentrated dose of Mad Milk.  Duration increases per hit to a max of 4 seconds."},
"rocket specialist":{"effect_type":"positive","description_string":"+15% rocket speed per point.  On direct hits: rocket does maximum damage, stuns target, and blast radius increased +15% per point."},
"SET BONUS: move speed set bonus":{"effect_type":"positive","description_string":"+X% faster move speed on wearer"},
"SET BONUS: health regen set bonus":{"effect_type":"positive","description_string":"+X health regenerated per second on wearer"},
"SET BONUS: dmg taken from crit reduced set bonus":{"effect_type":"positive","description_string":"+X% critical hit damage resistance on wearer"},
"SET BONUS: dmg taken from fire reduced set bonus":{"effect_type":"positive","description_string":"+X% fire damage resistance on wearer"},
"healing mastery":{"effect_type":"positive","description_string":"+25% heal rate for patient, +25% faster revive rate, and +25% self heal rate, per point."},
"kill eater 3":{"effect_type":"positive","description_string":""},
"kill eater score type 3":{"effect_type":"positive","description_string":""},
"strange restriction type 3":{"effect_type":"positive","description_string":""},
"strange restriction value 3":{"effect_type":"positive","description_string":""},
"bot custom jump particle":{"effect_type":"positive","description_string":""},
"generate rage on heal":{"effect_type":"positive","description_string":"Build energy by healing teammates.  When fully charged, press the Special-Attack key to deploy a frontal projectile shield."},
"custom name attr":{"effect_type":"positive","description_string":""},
"custom desc attr":{"effect_type":"positive","description_string":""},
"medigun bullet resist passive":{"effect_type":"positive","description_string":""},
"medigun blast resist passive":{"effect_type":"positive","description_string":""},
"medigun fire resist passive":{"effect_type":"positive","description_string":""},
"medigun bullet resist deployed":{"effect_type":"positive","description_string":""},
"medigun blast resist deployed":{"effect_type":"positive","description_string":""},
"medigun fire resist deployed":{"effect_type":"positive","description_string":""},
"medigun crit bullet percent bar deplete":{"effect_type":"positive","description_string":""},
"medigun crit blast percent bar deplete":{"effect_type":"positive","description_string":""},
"medigun crit fire percent bar deplete":{"effect_type":"positive","description_string":""},
"throwable fire speed":{"effect_type":"positive","description_string":""},
"throwable damage":{"effect_type":"positive","description_string":""},
"throwable healing":{"effect_type":"positive","description_string":""},
"throwable particle trail only":{"effect_type":"neutral","description_string":""},
"SET BONUS: dmg taken from bullets increased":{"effect_type":"negative","description_string":"X% bullet damage vulnerability on wearer"},
"SET BONUS: max health additive bonus":{"effect_type":"positive","description_string":"+X max health on wearer"},
"scattergun knockback mult":{"effect_type":"positive","description_string":""},
"particle effect vertical offset":{"effect_type":"positive","description_string":""},
"particle effect use head origin":{"effect_type":"positive","description_string":""},
"use large smoke explosion":{"effect_type":"positive","description_string":""},
"damage causes airblast":{"effect_type":"positive","description_string":""},
"increased jump height from weapon":{"effect_type":"positive","description_string":"+X% greater jump height when active"},
"damage force increase":{"effect_type":"negative","description_string":"X% increase in push force taken from damage"},
"healing received bonus":{"effect_type":"positive","description_string":"+X% bonus healing from all sources"},
"afterburn immunity":{"effect_type":"positive","description_string":"Immune to the effects of afterburn."},
"decoded by itemdefindex":{"effect_type":"positive","description_string":""},
"hype decays over time":{"effect_type":"negative","description_string":"Hype Decays Over Time."},
"SET BONUS: custom taunt particle attr":{"effect_type":"positive","description_string":"Extra effects when taunting."},
"airblast vulnerability multiplier hidden":{"effect_type":"negative","description_string":"+X% increased airblast vulnerability"},
"damage force increase hidden":{"effect_type":"negative","description_string":"X% increase in push force taken from damage"},
"damage force increase text":{"effect_type":"negative","description_string":"Increase in push force taken from damage and airblast"},
"SET BONUS: calling card on kill":{"effect_type":"positive","description_string":"Leave a Calling Card on your victims."},
"righthand pose parameter":{"effect_type":"neutral","description_string":""},
"set throwable type":{"effect_type":"neutral","description_string":""},
"add head on hit":{"effect_type":"positive","description_string":"#Attrib_AddHeadOnHit"},
"item style override":{"effect_type":"neutral","description_string":""},
"paint decal enum":{"effect_type":"neutral","description_string":""},
"show paint description":{"effect_type":"neutral","description_string":""},
"bot medic uber health threshold":{"effect_type":"neutral","description_string":""},
"bot medic uber deploy delay duration":{"effect_type":"neutral","description_string":""},
"single wep deploy time decreased":{"effect_type":"positive","description_string":"This weapon deploys X% faster"},
"halloween reload time decreased":{"effect_type":"positive","description_string":""},
"halloween fire rate bonus":{"effect_type":"positive","description_string":""},
"halloween increased jump height":{"effect_type":"positive","description_string":""},
"special taunt":{"effect_type":"positive","description_string":""},
"revive":{"effect_type":"positive","description_string":"Revive Teammates"},
"taunt attack name":{"effect_type":"positive","description_string":""},
"taunt attack time":{"effect_type":"positive","description_string":""},
"taunt force move forward":{"effect_type":"positive","description_string":""},
"taunt mimic":{"effect_type":"positive","description_string":""},
"taunt success sound":{"effect_type":"positive","description_string":"#Attrib_TauntSoundSuccess"},
"taunt success sound offset":{"effect_type":"positive","description_string":"#Attrib_PhaseCloak"},
"taunt success sound loop":{"effect_type":"positive","description_string":"#Attrib_TauntSoundSuccess"},
"taunt success sound loop offset":{"effect_type":"positive","description_string":"#Attrib_PhaseCloak"},
"increased air control":{"effect_type":"positive","description_string":"X% increased air control."},
"rocket launch impulse":{"effect_type":"positive","description_string":"#Attrib_RocketLaunchImpulse"},
"minicritboost on kill":{"effect_type":"positive","description_string":"On Kill: Gain Mini-crits for X seconds."},
"no metal from dispensers while active":{"effect_type":"negative","description_string":"No metal from dispensers when active."},
"projectile entity name":{"effect_type":"positive","description_string":""},
"is throwable primable":{"effect_type":"positive","description_string":""},
"throwable detonation time":{"effect_type":"positive","description_string":""},
"throwable recharge time":{"effect_type":"positive","description_string":""},
"closerange backattack minicrits":{"effect_type":"positive","description_string":"Mini-crits targets when fired at their back from close range"},
"torso scale":{"effect_type":"negative","description_string":""},
"rocketjump attackrate bonus":{"effect_type":"positive","description_string":"Increased attack speed and smaller blast radius while blast jumping"},
"is throwable chargeable":{"effect_type":"positive","description_string":""},
"back headshot":{"effect_type":"positive","description_string":"#Attrib_BackHeadshot"},
"rj air bombardment":{"effect_type":"positive","description_string":"Fires 3 barrages while explosive jumping"},
"projectile particle name":{"effect_type":"positive","description_string":""},
"air jump on attack":{"effect_type":"positive","description_string":"#Attrib_AirJumpOnAttack"},
"sniper crit no scope":{"effect_type":"positive","description_string":"Charge and fire shots independent of zoom"},
"sniper independent zoom DISPLAY ONLY":{"effect_type":"positive","description_string":"Zoom does not affect charge"},
"axtinguisher properties":{"effect_type":"positive","description_string":"100% critical hits burning players from behind.nMini-crits burning players from the front."},
"full charge turn control":{"effect_type":"positive","description_string":"Full turning control while charging"},
"parachute attribute":{"effect_type":"positive","description_string":""},
"taunt force weapon slot":{"effect_type":"positive","description_string":""},
"mini rockets":{"effect_type":"positive","description_string":""},
"rocket jump damage reduction HIDDEN":{"effect_type":"positive","description_string":"X% blast damage from rocket jumps"},
"clipsize increase on kill":{"effect_type":"positive","description_string":"Clip size increased on kill"},
"breadgloves properties":{"effect_type":"positive","description_string":""},
"taunt turn speed":{"effect_type":"positive","description_string":""},
"sniper fires tracer HIDDEN":{"effect_type":"negative","description_string":"Fires tracer rounds"},
"fire rate bonus with reduced health":{"effect_type":"positive","description_string":"Fire rate increases as health decreases"},
"tag__summer2014":{"effect_type":"positive","description_string":"Rewarded for participating in the 2014 Summer Adventure."},
"crate generation code":{"effect_type":"positive","description_string":""},
"stickybomb fizzle time":{"effect_type":"negative","description_string":"Stickybombs fizzle X seconds after landing"},
"stickybomb charge rate":{"effect_type":"positive","description_string":"Max charge time decreased by X%"},
"grenade no bounce":{"effect_type":"positive","description_string":"Grenades have very little bounce and roll"},
"class select override vcd":{"effect_type":"positive","description_string":"#Attrib_Class_Select_Override_VCD"},
"custom projectile model":{"effect_type":"positive","description_string":""},
"lose demo charge on damage when charging":{"effect_type":"negative","description_string":"Taking damage while shield charging reduces remaining charging time"},
"grenade no spin":{"effect_type":"positive","description_string":""},
"grenade detonation damage penalty":{"effect_type":"negative","description_string":"X% damage on grenades that explode on timer"},
"taunt turn acceleration time":{"effect_type":"positive","description_string":""},
"taunt move acceleration time":{"effect_type":"positive","description_string":""},
"taunt move speed":{"effect_type":"positive","description_string":""},
"shuffle crate item def min":{"effect_type":"positive","description_string":""},
"shuffle crate item def max":{"effect_type":"positive","description_string":""},
"limited quantity item":{"effect_type":"neutral","description_string":""},
"SET BONUS: alien isolation xeno bonus pos":{"effect_type":"positive","description_string":"Increased Melee damage against Isolated Merc Set"},
"SET BONUS: alien isolation xeno bonus neg":{"effect_type":"negative","description_string":"Increased Nostromo Napalmer damage taken from Isolated Merc Set"},
"SET BONUS: alien isolation merc bonus pos":{"effect_type":"positive","description_string":"Increased Nostromo Napalmer damage against Isolationist Pack Set"},
"SET BONUS: alien isolation merc bonus neg":{"effect_type":"negative","description_string":"Increased Melee damage taken from Isolationist Pack Set"},
"disable weapon switch":{"effect_type":"negative","description_string":""},
"hand scale":{"effect_type":"negative","description_string":""},
"display duck leaderboard":{"effect_type":"positive","description_string":""},
"duck rating":{"effect_type":"positive","description_string":"Duck XP Level : X"},
"duck badge level":{"effect_type":"positive","description_string":"Duck Power : X / 5"},
"tag__eotlearlysupport":{"effect_type":"positive","description_string":"Early Supporter of End of the Line Community Update"},
"unlimited quantity hidden":{"effect_type":"positive","description_string":""},
"duckstreaks active":{"effect_type":"positive","description_string":"Duckstreaks Active"},
"panic_attack":{"effect_type":"positive","description_string":"Hold fire to load up to 4 shells"},
"panic_attack_negative":{"effect_type":"negative","description_string":"Weapon spread increases as health decreases"},
"auto fires full clip penalty":{"effect_type":"negative","description_string":""},
"auto fires when full":{"effect_type":"negative","description_string":""},
"force weapon switch":{"effect_type":"positive","description_string":""},
"weapon_uses_stattrak_module":{"effect_type":"strange","description_string":""},
"is_operation_pass":{"effect_type":"neutral","description_string":""},
"weapon_stattrak_module_scale":{"effect_type":"neutral","description_string":""},
"set_item_texture_wear":{"effect_type":"neutral","description_string":""},
"cloak_consume_on_feign_death_activate":{"effect_type":"negative","description_string":"X% cloak meter when Feign Death is activated"},
"stickybomb_charge_damage_increase":{"effect_type":"positive","description_string":"Up to +X% damage based on charge"},
"NoCloakWhenCloaked":{"effect_type":"negative","description_string":"No cloak meter from ammo boxes when invisible"},
"ReducedCloakFromAmmo":{"effect_type":"negative","description_string":"X% cloak meter from ammo boxes"},
"elevate to unusual if applicable":{"effect_type":"positive","description_string":"#Attrib_ElevateQuality"},
"weapon_allow_inspect":{"effect_type":"neutral","description_string":""},
"metal_pickup_decreased":{"effect_type":"negative","description_string":"X% less metal from pickups and dispensers"},
"lose hype on take damage":{"effect_type":"negative","description_string":"Boost reduced when hit"},
"healing received penalty":{"effect_type":"negative","description_string":"X% less healing from all sources"},
"crit_vs_burning_FLARES_DISPLAY_ONLY":{"effect_type":"positive","description_string":"100% critical hit vs burning players"},
"speed_boost_on_kill":{"effect_type":"positive","description_string":"Gain a speed boost on kill"},
"speed_boost_on_hit":{"effect_type":"positive","description_string":"Gain a speed boost on hit"},
"spunup_damage_resistance":{"effect_type":"positive","description_string":"X% damage resistance when below 50% health and spun up"},
"ubercharge overheal rate penalty":{"effect_type":"negative","description_string":"X% �berCharge rate on Overhealed patients"},
"reduced_healing_from_medics":{"effect_type":"negative","description_string":"X% less healing from Medic sources"},
"health on radius damage":{"effect_type":"positive","description_string":"On Hit: Gain up to +X health per attack"},
"style changes on strange level":{"effect_type":"neutral","description_string":""},
"cannot restore":{"effect_type":"neutral","description_string":""},
"hide crate series number":{"effect_type":"neutral","description_string":""},
"has team color paintkit":{"effect_type":"neutral","description_string":"Team Colored Decorated Weapon"},
"cosmetic_allow_inspect":{"effect_type":"neutral","description_string":""},
"hat only unusual effect":{"effect_type":"unusual","description_string":""},
"items traded in for":{"effect_type":"neutral","description_string":"Items Traded in : X"},
"texture_wear_default":{"effect_type":"neutral","description_string":""},
"taunt only unusual effect":{"effect_type":"unusual","description_string":""},
"deactive date":{"effect_type":"neutral","description_string":""},
"is giger counter":{"effect_type":"neutral","description_string":""},
"hide_strange_prefix":{"effect_type":"neutral","description_string":""},
"always_transmit_so":{"effect_type":"neutral","description_string":""},
"allow_halloween_offering":{"effect_type":"neutral","description_string":""},
"cannot_transmute":{"effect_type":"neutral","description_string":""},
"single wep holster time increased":{"effect_type":"negative","description_string":"This weapon holsters X% slower"},
"single wep deploy time increased":{"effect_type":"negative","description_string":"This weapon deploys X% slower"},
"charge time decreased":{"effect_type":"negative","description_string":"X sec decrease in charge duration"},
"dmg penalty vs buildings":{"effect_type":"negative","description_string":"X% damage penalty vs buildings"},
"charge impact damage decreased":{"effect_type":"negative","description_string":"X% decrease in charge impact damage"},
"non economy":{"effect_type":"neutral","description_string":"Not Tradable, Usable in Crafting, or Gift Wrappable"},
"charge meter on hit":{"effect_type":"positive","description_string":"Melee hits refill X% of your charge meter."},
"minicrit_boost_when_charged":{"effect_type":"positive","description_string":"Secondary fire when charged grants mini-crits for X seconds."},
"minicrit_boost_charge_rate":{"effect_type":"positive","description_string":"Dealing damage fills charge meter."},
"is_a_sword":{"effect_type":"neutral","description_string":"This Weapon has a large melee range andndeploys and holsters slower"},
"ammo gives charge":{"effect_type":"positive","description_string":"Ammo boxes collected also give Charge"},
"extinguish restores health":{"effect_type":"positive","description_string":"Extinguishing teammates restores X health"},
"extinguish reduces cooldown":{"effect_type":"positive","description_string":"Extinguishing teammates reduces cooldown by X%"},
"cannot giftwrap":{"effect_type":"neutral","description_string":""},
"tool needs giftwrap":{"effect_type":"neutral","description_string":""},
"fuse bonus":{"effect_type":"positive","description_string":"X% fuse time on grenades"},
"move speed bonus shield required":{"effect_type":"positive","description_string":"+X% faster move speed on wearer (shield required)"},
"damage bonus vs sentry target":{"effect_type":"positive","description_string":"X% increased damage to your sentry's target"},
"mod teleporter cost":{"effect_type":"positive","description_string":"X% metal cost when constructing or upgrading teleporters"},
"damage blast push":{"effect_type":"positive","description_string":"#Attrib_DamageBlastPush"},
"move speed bonus resource level":{"effect_type":"positive","description_string":""},
"hype on damage":{"effect_type":"positive","description_string":"On Hit: Builds Hype"},
"dmg taken from fire reduced on active":{"effect_type":"positive","description_string":"+X% fire damage resistance while deployed"},
"damage bonus vs burning":{"effect_type":"positive","description_string":"X% damage vs burning players"},
"min_viewmodel_offset":{"effect_type":"neutral","description_string":""},
"dmg pierces resists absorbs":{"effect_type":"positive","description_string":"Attacks pierce damage resistance effects and bonuses"},
"energy buff dmg taken multiplier":{"effect_type":"negative","description_string":""},
"lose revenge crits on death DISPLAY ONLY":{"effect_type":"negative","description_string":"Revenge crits are lost on death"},
"CARD: damage bonus":{"effect_type":"positive","description_string":"+X% damage bonus"},
"CARD: dmg taken from bullets reduced":{"effect_type":"positive","description_string":"+X% bullet damage resistance on wearer"},
"CARD: move speed bonus":{"effect_type":"positive","description_string":"+X% faster move speed on wearer"},
"CARD: health regen":{"effect_type":"positive","description_string":"+X health regenerated per second on wearer"},
"SPELL: set item tint RGB":{"effect_type":"positive","description_string":"X"},
"SPELL: set Halloween footstep type":{"effect_type":"positive","description_string":"X"},
"SPELL: Halloween voice modulation":{"effect_type":"positive","description_string":"Voices From Below"},
"SPELL: Halloween pumpkin explosions":{"effect_type":"positive","description_string":"Pumpkin Bombs"},
"SPELL: Halloween green flames":{"effect_type":"positive","description_string":"Halloween Fire"},
"SPELL: Halloween death ghosts":{"effect_type":"positive","description_string":"Exorcism"},
"Attack not cancel charge":{"effect_type":"positive","description_string":""},
"recipe component defined item 1":{"effect_type":"neutral","description_string":""},
"recipe component defined item 2":{"effect_type":"neutral","description_string":""},
"recipe component defined item 3":{"effect_type":"neutral","description_string":""},
"recipe component defined item 4":{"effect_type":"neutral","description_string":""},
"recipe component defined item 5":{"effect_type":"neutral","description_string":""},
"recipe component defined item 6":{"effect_type":"neutral","description_string":""},
"recipe component defined item 7":{"effect_type":"neutral","description_string":""},
"recipe component defined item 8":{"effect_type":"neutral","description_string":""},
"recipe component defined item 9":{"effect_type":"neutral","description_string":""},
"recipe component defined item 10":{"effect_type":"neutral","description_string":""},
"start drop date":{"effect_type":"neutral","description_string":""},
"end drop date":{"effect_type":"neutral","description_string":""},
"tool target item":{"effect_type":"neutral","description_string":""},
"killstreak effect":{"effect_type":"positive","description_string":"Killstreaker: X"},
"killstreak idleeffect":{"effect_type":"positive","description_string":"Sheen: X"},
"spellbook page attr id":{"effect_type":"neutral","description_string":""},
"Halloween Spellbook Page: Tumidum":{"effect_type":"positive","description_string":"Pages of Tumidum: X"},
"Halloween Spellbook Page: Gratanter":{"effect_type":"positive","description_string":"Pages of Gratanter: X"},
"Halloween Spellbook Page: Audere":{"effect_type":"positive","description_string":"Pages of Audere: X"},
"Halloween Spellbook Page: Congeriae":{"effect_type":"positive","description_string":"Pages of Congeriae: X"},
"Halloween Spellbook Page: Veteris":{"effect_type":"positive","description_string":"Pages of Veteris: X"},
"additional halloween response criteria name":{"effect_type":"positive","description_string":""},
"loot rarity":{"effect_type":"neutral","description_string":""},
"quality text override":{"effect_type":"neutral","description_string":""},
"item name text override":{"effect_type":"neutral","description_string":""},
"killstreak tier":{"effect_type":"positive","description_string":"Killstreaks Active"},
"wide item level":{"effect_type":"neutral","description_string":""},
"is australium item":{"effect_type":"neutral","description_string":""},
"is marketable":{"effect_type":"neutral","description_string":""},
"allowed in medieval mode":{"effect_type":"neutral","description_string":""},
"crit on hard hit":{"effect_type":"positive","description_string":""},
"series number":{"effect_type":"neutral","description_string":""},
"recipe no partial complete":{"effect_type":"neutral","description_string":""},
"kill refills meter":{"effect_type":"positive","description_string":"Melee kills refill X% of your charge meter."},
"random drop line item unusual chance":{"effect_type":"neutral","description_string":""},
"random drop line item unusual list":{"effect_type":"neutral","description_string":""},
"random drop line item 0":{"effect_type":"neutral","description_string":""},
"random drop line item 1":{"effect_type":"neutral","description_string":""},
"random drop line item 2":{"effect_type":"neutral","description_string":""},
"random drop line item 3":{"effect_type":"neutral","description_string":""},
"on taunt attach particle index":{"effect_type":"unusual","description_string":" Unusual Effect: X"},
"loot list name":{"effect_type":"neutral","description_string":""},
"upgrade rate decrease":{"effect_type":"negative","description_string":"X% slower upgrade rate"},
"can shuffle crate contents":{"effect_type":"neutral","description_string":""},
"random drop line item footer desc":{"effect_type":"neutral","description_string":""},
"is commodity":{"effect_type":"neutral","description_string":""},
"voice pitch scale":{"effect_type":"negative","description_string":"Disables double jump"},
"gunslinger punch combo":{"effect_type":"positive","description_string":"Third successful punch in a row always crits."},
"cannot delete":{"effect_type":"neutral","description_string":""},
"quest loaner id low":{"effect_type":"neutral","description_string":""},
"quest loaner id hi":{"effect_type":"neutral","description_string":""},
"is festive":{"effect_type":"unusual","description_string":"Festivized"},
"item slot criteria 1":{"effect_type":"neutral","description_string":""},
"item in slot 1":{"effect_type":"neutral","description_string":""},
"item slot criteria 2":{"effect_type":"neutral","description_string":""},
"item in slot 2":{"effect_type":"neutral","description_string":""},
"item slot criteria 3":{"effect_type":"neutral","description_string":""},
"item in slot 3":{"effect_type":"neutral","description_string":""},
"item slot criteria 4":{"effect_type":"neutral","description_string":""},
"item in slot 4":{"effect_type":"neutral","description_string":""},
"item slot criteria 5":{"effect_type":"neutral","description_string":""},
"item in slot 5":{"effect_type":"neutral","description_string":""},
"item slot criteria 6":{"effect_type":"neutral","description_string":""},
"item in slot 6":{"effect_type":"neutral","description_string":""},
"item slot criteria 7":{"effect_type":"neutral","description_string":""},
"item in slot 7":{"effect_type":"neutral","description_string":""},
"item slot criteria 8":{"effect_type":"neutral","description_string":""},
"item in slot 8":{"effect_type":"neutral","description_string":""},
"quest earned standard points":{"effect_type":"neutral","description_string":""},
"quest earned bonus points":{"effect_type":"neutral","description_string":""},
"item drop wave":{"effect_type":"neutral","description_string":""},
"add head on kill":{"effect_type": "positive", "description_string": "Collect the organs of your victims"},
"mult spread scales consecutive":{"effect_type":"negative","description_string":" Successive shots become less accurate"},
"fixed shot pattern":{"effect_type":"positive","description_string":"Fires a wide, fixed shot pattern"},
"ubercharge preserved on spawn max":{"effect_type":"positive","description_string":"Collect the organs of people you hit"},
"mod air control blast jump":{"effect_type":"positive","description_string":"%s1% increased air control when blast jumping."},
"spunup push force immunity":{"effect_type":"positive","description_string":"Immune to push force from damage and airblast when spun up"},
"airblast_destroy_projectile":{"effect_type": "neutral", "description_string": "Attrib_AirblastDestroyProjectile"},
"airblast_pushback_disabled":{"effect_type": "negative", "description_string": ""},
"airblast_pushback_no_stun":{"effect_type":"negative","description_string":""},
"airblast_pushback_no_viewpunch":{"effect_type":"negative","description_string":""},
"airblast_deflect_projectiles_disabled":{"effect_type":"negative","description_string":""},
"airblast_put_out_teammate_disabled":{"effect_type":"negative","description_string":""},
"afterburn duration penalty":{"effect_type":"negative","description_string":""},
"afterburn duration bonus":{"effect_type":"positive","description_string":""},
"aoe_deflection":{"effect_type":"neutral","description_string":""},
"mult_end_flame_size":{"effect_type":"positive","description_string":""},
"airblast_give_teammate_speed_boost":{"effect_type":"positive","description_string":""},
"airblast_turn_projectile_to_ammo":{"effect_type":"neutral","description_string":""},
"redirected_flame_size_mult":{"effect_type":"positive","description_string":""},
"flame_reflect_on_collision":{"effect_type":"positive","description_string":""},
"flame_spread_degree":{"effect_type":"positive","description_string":""},
"flame_gravity":{"effect_type":"neutral","description_string":""},
"flame_ignore_player_velocity":{"effect_type":"neutral","description_string":""},
"flame_drag":{"effect_type":"neutral","description_string":""},
"flame_speed":{"effect_type":"neutral","description_string":""},
    "max_flame_reflection_count":{"effect_type":"neutral","description_string":""},
    "flame_reflection_add_life_time":{"effect_type":"neutral","description_string":""},
    "reflected_flame_dmg_reduction":{"effect_type":"neutral","description_string":""},
    "flame_lifetime":{"effect_type":"neutral","description_string":""},
    "flame_random_life_time_offset":{"effect_type":"neutral","description_string":""},
    "flame_up_speed":{"effect_type":"neutral","description_string":""},
    "crit_dmg_falloff":{"effect_type":"negative","description_string":" Critical damage is affected by range "},
    "crits_become_minicrits":{"effect_type":"negative","description_string":"Minicrits whenever it would normally crit "},
    "falling_impact_radius_pushback":{"effect_type":"positive","description_string":" Push enemies back when you land (force and radius based on velocity)"},
    "falling_impact_radius_stun":{"effect_type":"positive","description_string":"Stun enemies when you land"},
    "thermal_thruster_air_launch":{"effect_type":"positive","description_string":"Able to re-launch while already in-flight"},
    "thermal_thruster":{"effect_type":"positive", "description_string":""},
    "explode_on_ignite":{"effect_type":"positive","description_string":"Ignited enemies explode"},
    "attack_minicrits_and_consumes_burning":{"effect_type":"positive","description_string":"Attacks consume burning status on targets to mini-crit"},
    "paintkit_proto_def_index":{"effect_type":"neutral","description_string":"Warpaint base"},
}